name: Django CD  # Workflow name
on:
  pull_request:
    types:
      - closed
    branches: [ main ]

jobs:
  cd:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.11.0 
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.0 

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setting .env
        run: |
          echo "${{ secrets.ENV }}" >> .env
          cat .env

      - name: Build docker images
        run: |
          docker-compose -f docker-compose.prod.yml build
          docker images

      - name: Push docker images 
        run: docker-compose -f docker-compose.prod.yml push

      - uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.AWS_HOST}}
          username: ${{secrets.AWS_USERNAME}}
          key: ${{ secrets.AWS_KEY_PEM }}
          envs: GITHUB_SHA
          script: |
            mkdir test
          # script: |
          #   docker pull [계정명]/spring-cicd:${GITHUB_SHA::7}
          #   docker tag [계정명]/spring-cicd:${GITHUB_SHA::7} spring-cicd
          #   docker stop server
          #   docker run -d --rm --name server -p 80:8080 spring-cicd

