name: Django CD  # workflow 이름
on: # Event
  pull_request:
    types:
      - closed
    branches: [ main ]

jobs:
  cd:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.11.0 
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.0 
      
      # 의존성 설치
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          cd github_actions
          pip install -r requirements.txt

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setting .env
        run: |
          echo "${{ secrets.ENV }}" >> .env
          cat .env

      - name: Build docker images
        run: |
          docker-compose -f docker-compose.prod.yml build
          docker images

      - name: Push docker images 
        run: docker-compose -f docker-compose.prod.yml push

      - uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.AWS_HOST}}
          username: ${{secrets.AWS_USERNAME}}
          key: ${{ secrets.AWS_KEY_PEM }}
          envs: GITHUB_SHA
          script: |
              cd github_actions_session
              git pull
              sudo docker-compose -f docker-compose.prod.yml down
              sudo docker-compose -f docker-compose.prod.yml pull
              sudo docker-compose -f docker-compose.prod.yml up -d