name: Django CI # workflow 이름

on: # Event
  push:
    branches:
      - main
#     - develop (다른 브랜치도 추가 가능)
  pull_request:
    branches:
      - main

jobs: # Job
  ci: # Job 이름
    runs-on: ubuntu-latest # Runner
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.11.0 ]
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.DATABASE }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v2

    - name: Verify MySQL connection
      run: |
        mysql --version
        mysql --host 127.0.0.1 --port 3306 -u ${{ secrets.MYSQL_USERNAME }} -p${{ secrets.MYSQL_ROOT_PASSWORD }}

    - name: Set up Python 3.11.0 
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.0 

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run migrations
      run: |
        cd github_actions
        python manage.py migrate

    - name: Run Tests
      run: |
        cd github_actions
        mysql --host 127.0.0.1 --port 3306 -u ${{ secrets.MYSQL_USERNAME }} -p${{ secrets.MYSQL_ROOT_PASSWORD }}"
        python manage.py test
      env:
        SYSTEM_ENV: GITHUB_WORKFLOW